env:
    browser: true
    es2021: true
extends:
    - eslint:recommended
    - plugin:react/recommended
    - plugin:prettier/recommended
overrides: []
parserOptions:
    ecmaVersion: latest
    ecmaFeatures:
        experimentalObjectRestSpread: true
    sourceType: module
plugins:
    - prettier
rules:
    no-unused-vars:
        - 'off'
    quotes:
        - warn
        - double
    semi:
        - warn
        - always
    no-undef:
        - warn
    no-undefined:
        - warn
    prettier/prettier:
        - off
    react/prop-types:
        - off
    react/react-in-jsx-scope:
        - off
